version: "3.9"
services:
  caddy:
    image: caddy:2.5.2-alpine
    container_name: ghost-prod-caddy
    depends_on:
      - ghost
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  web:
    build: .
    ports:
      - "3000:3000"