name: Documentation Issue
description: Report an issue with our documentation
title: "[Documentation]: "
labels: ["documentation", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue you're having with the documentation.
      placeholder: Tell us what you're seeing!
    validations:
      required: true
  - type: input
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have an idea of how this issue could be resolved, please describe it here.
      placeholder: ex. Update the instructions to include XYZ
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Please provide any relevant examples, such as code snippets or screenshots, that would help us understand the issue.
      render: code
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true