name: General Issue
description: Report a general issue or request
title: "[General Issue]: "
labels: ["general", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our project!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue or request.
      placeholder: Tell us what you're seeing or what you'd like to see!
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue or request?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Please provide any relevant examples, such as code snippets or screenshots, that would help us understand the issue or request.
      render: code
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true