name: Production SSH upload, build and deploy

on: [workflow_dispatch, pull_request, push]

jobs:
  upload_files:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Upload files and Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload and deploy web app
      # See https://github.com/marketplace/actions/ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        user: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
        pass: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
        port: ${{ secrets.PRODUCTION_SERVER_PORT }}
        first_ssh: |
          rm -rf ./haidevs-website
          mkdir ./haidevs-website
        scp: |
          './*' => ./haidevs-website
        last_ssh: |
          cd ./haidevs-website &&
          docker-compose up -d --build